### ISSUE TITLE
I just downloaded your project and the code doesn't compile

### ISSUE THREAD

**Issue by jmelosegui** [net4u/GMap-Test#1]

**Comment by net4u** [comment]
I did not make (major) changes versus your original repository. I just tried to adapt models to my table layout.

**Comment by jmelosegui** [comment]
I would like to have a project that I can build. So try this. 

1. clone your repository into a new directory on your PC
2. open it with Visual Studio
3. Hit F5

You shouldn't get any errors after those steps.

**Comment by net4u** [comment]
I checked, it have missed your library project (In fact I skipped because it have the build dll in bin folder). I added and I build it without errors. But at run-time is the same error.

**Comment by net4u** [comment]
In fact I don't have run-time errors. Simply it render the map but is not visible. If I inspect the page I see the <div> generated for each marker from my table, but nothing visible.

**Comment by jmelosegui** [comment]
Hi @net4u 
Now you have working the Jobs page.
Notes
1. You should read the [installation page](https://github.com/jmelosegui/GooglemapMvc/wiki/Installation) to learn how to use the map.
2. Try to use the nuget package when possible
3. If you modify the jmelosegui.googlemap.js script file check the JavaScript console in your browser to be sure you do not have errors.

Good luck with your project.
